Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 559, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
def log_marginal_likelihood(l):
    kernel = ConstantKernel(constant_value=1.) * RBF(length_scale=l) + WhiteKernel(noise_level=0.)
    K = kernel(X, X)
    datafit = - np.matmul(Y.reshape(1, -1), np.linalg.solve(K, Y.reshape(-1, 1)))/2
    complexity = - np.log(np.linalg.det(K))
    lml = - X.shape[0]/2 * np.log(2*np.pi) + datafit + complexity
    return datafit[0], complexity, lml[0]
                        
length_scales = np.linspace(1e-5, 3.05, num=100)
datafits, complexities, lmls = [], [], []
for l in length_scales:
    datafit, complexity, lml = log_marginal_likelihood(l)
    datafits.append(datafit)
    complexities.append(complexity)
    lmls.append(lml)
                          
fig= plt.figure(figsize=(14, 10))
plt.plot(length_cales, datafits, label='data fit')
plt.plot(length_cales, complexities, label='minus complexity penalty')
plt.plot(length_cales, lmls, label='log marginal likelihood')
plt.vlines(length_scales[np.argmax(lmls)], plt.ylim()[0], np.max(lmls), colors='green', alpha=0.75, 
           linestyles='dashed', label='MLE estimate')
plt.legend()
plt.show()
                          
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/tmp/ipykernel_1780/2581928285.py[0m in [0;36m<module>[0;34m[0m
[1;32m     16[0m [0;34m[0m[0m
[1;32m     17[0m [0mfig[0m[0;34m=[0m [0mplt[0m[0;34m.[0m[0mfigure[0m[0;34m([0m[0mfigsize[0m[0;34m=[0m[0;34m([0m[0;36m14[0m[0;34m,[0m [0;36m10[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 18[0;31m [0mplt[0m[0;34m.[0m[0mplot[0m[0;34m([0m[0mlength_cales[0m[0;34m,[0m [0mdatafits[0m[0;34m,[0m [0mlabel[0m[0;34m=[0m[0;34m'data fit'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     19[0m [0mplt[0m[0;34m.[0m[0mplot[0m[0;34m([0m[0mlength_cales[0m[0;34m,[0m [0mcomplexities[0m[0;34m,[0m [0mlabel[0m[0;34m=[0m[0;34m'minus complexity penalty'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     20[0m [0mplt[0m[0;34m.[0m[0mplot[0m[0;34m([0m[0mlength_cales[0m[0;34m,[0m [0mlmls[0m[0;34m,[0m [0mlabel[0m[0;34m=[0m[0;34m'log marginal likelihood'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'length_cales' is not defined
NameError: name 'length_cales' is not defined

